[package]
name = "ldrawy"
version = "0.1.0"
edition = "2021"
include = ["/render"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
image = "*"